#-------------------------------------------------
#
# Project created by QtCreator 2017-02-09T14:53:18
#
#-------------------------------------------------

QT += core concurrent

CONFIG += c++11

TEMPLATE = lib

DEFINES += FACEDETECTORCORE_LIBRARY

SOURCES += Core.cpp \
    CorePrivate.cpp

HEADERS += Core.h\
        facedetector-core_global.h \
    CorePrivate.h \
    IAlgorithm.h \
    ImageProcessingResult.h


include(autogenerated.pri)
