#ifndef FACEDETECTORCORE_GLOBAL_H
#define FACEDETECTORCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACEDETECTORCORE_LIBRARY)
#  define FACEDETECTORCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACEDETECTORCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEDETECTORCORE_GLOBAL_H
