#-------------------------------------------------
#
# Project created by QtCreator 2017-02-09T14:39:22
#
#-------------------------------------------------

QT += core

CONFIG += c++11

TEMPLATE = lib

DEFINES += FACEDETECTORFAKEALGORITHM_LIBRARY

SOURCES += FakeAlgorithm.cpp

HEADERS += FakeAlgorithm.h\
        facedetector-fakealgorithm_global.h

INCLUDEPATH += \
    $$PWD/..

include(autogenerated.pri)
