#ifndef FACEDETECTORFAKEALGORITHM_GLOBAL_H
#define FACEDETECTORFAKEALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FACEDETECTORFAKEALGORITHM_LIBRARY)
#  define FACEDETECTORFAKEALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FACEDETECTORFAKEALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FACEDETECTORFAKEALGORITHM_GLOBAL_H
